#!/bin/bash

project=blank
license=MIT
repository=
docs=docs
name=

for arg in "$@"; do
	case "$arg" in

	--name=*)
        name=`echo $arg | sed 's/--name=//'`
    ;;

	--project=*)
        project=`echo $arg | sed 's/--project=//'`
    ;;

	--license=*)
        license=`echo $arg | sed 's/--license=//'`
    ;;

	--repository=*)
        repository=`echo $arg | sed 's/--repository=//'`
    ;;

	--help)
        echo 'usage: ./generator [options]'
        echo ''
        echo 'options:'
        echo '  --name=<name>: name of project'
        echo '  --project=<project>: target project (blank, html)'
		echo '  --license=<license>: license (AGPLv3, EUPLv1.2, GPLv3, MIT)'
		echo '  --repository=<repository>: repository (gitlab)'
        echo ''
        echo 'All invalid options are silently ignored!'
        exit 0
    ;;

	esac
done

if [ -z $name ]; then
	echo "You must specify name option"
	exit 0
fi

if [ -d ./generated/$name ]; then
	echo "Directory already exist"
	exit 0
fi

echo "Generating project $name..."

cp -rT ./templates/default/ ./generated/$name

if [ $project != "blank" ]; then
	cp -rT ./templates/configure/$project/ ./generated/$name
	cp -rT ./templates/projects/$project/ ./generated/$name
fi

echo "Add license $license..."
cp ./templates/LICENSE/$license ./generated/$name/LICENSE

documentation=./generated/$name/$docs

if [ ! -z $repository ]; then
	docs=.$repository
	documentation=./generated/$name/$docs

	if [ -d ./templates/CI/$project/$repository/ ]; then
		cp -rT ./templates/CI/$project/$repository/ $documentation
	fi
fi

cp -rT ./templates/docs/ $documentation

echo "Replace content in files.."

sed -i "s/{name}/$name/g" ./generated/$name/README.md
sed -i "s/{license}/$license/g" ./generated/$name/README.md
sed -i "s/{license}/$license/g" $documentation/CONTRIBUTING.md
sed -i "s/{docs.path}/$docs/g" ./generated/$name/README.md

if [ -f "./data.json" ]; then

	if [ ! $(command -v jq) &> /dev/null ]; then
		echo "jq must be present on your system"
		exit 0
	fi

	data=$(cat ./data.json)

	sed -i "s/{author.name}/$(echo $data | jq -r '.author.name')/g" ./generated/$name/README.md
	sed -i "s,{author.website},$(echo $data | jq -r '.author.website' ),g" ./generated/$name/README.md
	sed -i "s,{author.email},$(echo $data | jq -r '.author.email' ),g" $documentation/CODE_OF_CONDUCT.md

	counter=2
	for k in $(jq -c '.support[]' <<< $data); do
	    sed -i "$(awk "/^Is it possible to contact us by/{ print NR + $counter; exit }" $documentation/SUPPORT.md)s,.*,- [$(echo $k | jq -r '.name' )]($(echo $k | jq -r '.url' ))\\n," $documentation/SUPPORT.md
		counter=$((counter + 1))
	done
else
	echo ""
	echo "⚠️⚠️⚠️ If you want to pimp your documentation files, copy data.json.dist to data.json and add changes your data!"
	echo ""
fi

echo "Configuration complete"
